sudo: false

os:
  - linux

language: d

d:
  - ldc
  # TODO - dmd

env:
  - ARCH="x86_64"


before_install:
  - sudo apt-get install -qq libopenblas-dev

script:
  - dub test --arch "$ARCH" --build=unittest-cov

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - git clone https://github.com/adamdruppe/adrdox.git
  - cd adrdox && make ldc && cd -
  - ./adrdox/doc2 source
  - mv generate-docs docs

deploy:
  d: ldc
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master

